### ISSUE TITLE
Error: Can't extend QueryBuilder with existing method ('paginate').

### ISSUE THREAD

**Issue by sornman** [felixmosh/knex-paginate#1]
Looking into replacing knex-paginator with this, and it looks pretty easy. However, I am running into an issue. All of my routes are in separate files:

```
const someRoute = require('./some');
router.use('/some', someRoute);
const otherRoute = require('./other');
router.use('/other', otherRoute);
```

Then in the route files I have:
```
const knexConfig = require('../knexfile');
const knex = require('knex')(knexConfig);
const { attachPaginate } = require('knex-paginate');
attachPaginate();
```

When I just have 1 route it works fine, but when I have all of them loaded, it gives the following error:
```
[dev.server] Error: Can't extend QueryBuilder with existing method ('paginate').
[dev.server]     at Function.Builder.extend (/var/www/user-audit/server/node_modules/knex/lib/query/builder.js:1287:11)
[dev.server]     at Object.extend (/var/www/user-audit/server/node_modules/knex/lib/knex.js:63:18)
[dev.server]     at attachPaginate (/var/www/user-audit/server/node_modules/knex-paginate/lib/index.js:4:21)
[dev.server]     at Object.<anonymous> (/var/www/user-audit/server/routes/campus.js:7:1)
[dev.server]     at Module._compile (internal/modules/cjs/loader.js:774:30)
[dev.server]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
[dev.server]     at Module.load (internal/modules/cjs/loader.js:641:32)
[dev.server]     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
[dev.server]     at Module.require (internal/modules/cjs/loader.js:681:19)
[dev.server]     at require (internal/modules/cjs/helpers.js:16:16)
[dev.server]     at Object.<anonymous> (/var/www/user-audit/server/routes/index.js:43:21)
[dev.server]     at Module._compile (internal/modules/cjs/loader.js:774:30)
[dev.server]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
[dev.server]     at Module.load (internal/modules/cjs/loader.js:641:32)
[dev.server]     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
[dev.server]     at Module.require (internal/modules/cjs/loader.js:681:19)
```

Am I doing something wrong? If so, what should I do to resolve the issue? The code was working fine with knex-paginator with minor tweaks.

**Comment by sornman** [comment]
Thanks! I figured as much from the error message, but just wanted to make sure there wasn't something else going on.

**Comment by bmitchinson** [comment]
For those snooping, I came across this issue when testing my API with jest.

This guard clause helped me avoid reassignment

```typescript
    getConnection(): Knex {
        if (!this.connection) {
            this.connection = Knex({
                client: this.client,
                connection: this.connectionConfig,
                migrations: this.migrationConfig,
                seeds: this.seedConfig
            })
            /* 
                If the queryBuilder already has been extended to include pagination, don't attempt re-assignment.
                This guard is needed to stop unit tests from attempting duplicate extension of the queryBuilder.
            */
            if (!this.connection.queryBuilder().paginate) {
                attachPaginate()
            }
        }
        return this.connection
    }
```
